#
# Project Api context crates configuration
---
Hlx\Security\SecurityCrate:
  settings:
    roles:
      access_rules:
        - [ '^/logout$', 'ROLE_USER' ]
    authenticators:
      hlx.security.header_token_authenticator: Hlx\Security\Authentication\TokenAuthenticator
    firewalls:
      default:
        stateless: true
        guard:
          authenticators:
            - hlx.security.header_token_authenticator