#
# Project Web context crates configuration
---
Hlx\Security\SecurityCrate:
  settings:
    roles:
      access_rules:
        - [ '^/login$', 'IS_AUTHENTICATED_ANONYMOUSLY' ]
    auto_login:
      enabled: true
      firewall: default
      target_path: home
    oauth:
      facebook:
        enabled: false
        app_key: '${oauth.facebook.app_key}'
        app_secret: '${oauth.facebook.app_secret}'
        scope: [ public_profile, email ]
        fields: [ id, name, email, first_name, last_name ]
        field_mapping:
          firstname: first_name
          lastname: last_name
    authenticators:
      hlx.security.form_login_authenticator: Hlx\Security\Authentication\FormLoginAuthenticator
      hlx.security.user_token_authenticator: Hlx\Security\Authentication\UserTokenAuthenticator
    firewalls:
      default:
        guard:
          authenticators:
            - hlx.security.form_login_authenticator
            - hlx.security.user_token_authenticator
          entry_point: hlx.security.form_login_authenticator
        logout:
          target_url: /
          logout_path: /logout
          invalidate_session: true
          with_csrf: true
        remember_me:
          key: Soob3iGsh9oM
          lifetime: 1209000