#
# Project Web context crates configuration
---
Hlx\Security\SecurityCrate:
  settings:
    auto_login:
      enabled: true
      firewall: default
      target_path: home
    oauth:
      facebook:
        enabled: false
        app_key: ${oauth.facebook.app_key}
        app_secret: ${oauth.facebook.app_secret}
        scope: [ public_profile, email ]
        fields: [ id, name, email, first_name, last_name ]
        field_mapping: { firstname: first_name, lastname: last_name }
    firewalls:
      default:
        form:
          default_target_path: /
        logout:
          target_url: /
        remember_me:
          key: Soob3iGsh9oM
          lifetime: 1209000
