#
# Project crates configuration
---
Hlx\Security\SecurityCrate:
  settings:
    routing_prefix: /
    roles:
      default_role: user
      available_roles:
        - user
        - administrator
    recaptcha:
      enabled: false
      site_key: '${recaptcha.site_key}'
      secret_key: '${recaptcha.secret_key}'
    voters:
      - Hlx\Security\Voter\OwnershipVoter