#
# Project settings:
---
project:
  name: Honeylex-CMF
  description: 'Honeybee CQRS & ES integration with the Silex framework'
  app:
    prefix: honeylex-cmf
  database:
    prefix: honeylex-cmf
  email:
    from_email: honeylex-cmf@honeylex.dev
    from_name: Honeylex CMF
  translation:
    default_locale: en
    locale_fallbacks: [ en, de ]

local_configs:
  recaptcha:
    name: recaptcha.json
    type: json
    load: from_file
  oauth:
    name: oauth.json
    type: json
    load: from_file
