#
# Project translations
---
en:
  messages:
    'Honeybee CQRS & ES integration with the Silex framework': 'Honeybee CQRS & ES integration with the Silex framework'
  locale:
    'en': English
    'de': Deutsch
    'fr': Français
    'es': Español
    'ja': 日本語
    'ar': عربى

de:
  messages:
    'Honeybee CQRS & ES integration with the Silex framework': 'Honeybee CQRS & ES Integration mit dem Silex framework'
