version: "3.1"
volumes:
  logs:
secrets:
  couchdb.json:
    file: ../secrets/default/couchdb.json
  elasticsearch.json:
    file: ../secrets/default/elasticsearch.json
  rabbitmq.json:
    file: ../secrets/default/rabbitmq.json
  swiftmailer.json:
    file: ../secrets/default/swiftmailer.json
  recaptcha.json:
    file: ../secrets/default/recaptcha.json
  oauth.json:
    file: ../secrets/default/oauth.json
services:
  proxy:
    image: blacklabelops/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_REDIRECT_PORT80: "true"
      SERVER1SERVER_NAME: ${HOST_NAME}
      SERVER1HTTP_ENABLED: "false"
      SERVER1HTTPS_ENABLED: "true"
      SERVER1REVERSE_PROXY_LOCATION1: /
      SERVER1REVERSE_PROXY_PASS1: http://nginx:8000
      SERVER1PROXY_APPLICATION: custom
      SERVER1REVERSE_PROXY_HEADER1FIELD1: X-Forwarded-Host ${HOST_NAME}
      SERVER1REVERSE_PROXY_HEADER1FIELD2: X-Forwarded-Proto ${HOST_SCHEME}
      SERVER1REVERSE_PROXY_HEADER1FIELD3: X-Forwarded-For $$proxy_add_x_forwarded_for
      SERVER2SERVER_NAME: api.${HOST_NAME}
      SERVER2HTTP_ENABLED: "false"
      SERVER2HTTPS_ENABLED: "true"
      SERVER2REVERSE_PROXY_LOCATION1: /
      SERVER2REVERSE_PROXY_PASS1: http://nginx:8001
      SERVER2PROXY_APPLICATION: custom
      SERVER2REVERSE_PROXY_HEADER1FIELD1: X-Forwarded-Host ${HOST_NAME}
      SERVER2REVERSE_PROXY_HEADER1FIELD2: X-Forwarded-Proto ${HOST_SCHEME}
      SERVER2REVERSE_PROXY_HEADER1FIELD3: X-Forwarded-For $$proxy_add_x_forwarded_for

  nginx:
    image: nginx:stable
    command: ["nginx", "-c", "/var/www/var/docker/nginx/conf/nginx.conf", "-g", "daemon off;"]
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - php_fpm:php_fpm

  php_cli:
    image: friendsofhoneybee/php:5.6-cli
    working_dir: /var/www
    links:
      - couchdb:couchdb
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    secrets:
      - couchdb.json
      - elasticsearch.json
      - rabbitmq.json
      - swiftmailer.json
      - recaptcha.json
      - oauth.json
    environment:
      - APP_VERSION
      - APP_ENV
      - APP_DEBUG
      - HOST_SCHEME
      - HOST_NAME
      - LOCAL_CONFIG_DIR
      - PHP_INI_SCAN_DIR=var/docker/php/cli/conf/conf.d

  php_fpm:
    image: friendsofhoneybee/php:5.6-fpm
    command: ["php-fpm", "-R", "-y", "/var/www/var/docker/php/fpm/conf/php-fpm.d/www.conf"]
    working_dir: /var/www
    ports:
      - "9000:9000"
    links:
      - couchdb:couchdb
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    secrets:
      - couchdb.json
      - elasticsearch.json
      - rabbitmq.json
      - swiftmailer.json
      - recaptcha.json
      - oauth.json
    environment:
      - APP_VERSION
      - APP_ENV
      - APP_DEBUG
      - LOCAL_CONFIG_DIR
      - PHP_INI_SCAN_DIR=var/docker/php/fpm/conf/conf.d

  couchdb:
    image: couchdb:1
    ports:
      - "5984:5984"

  elasticsearch:
    image: friendsofhoneybee/elasticsearch:2.4
    command: ["elasticsearch", "--path.conf=/usr/local/elasticsearch/conf"]
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: friendsofhoneybee/rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS