version: '2'
services:
  proxy:
    image: blacklabelops/nginx:latest
    ports:
      - "80:80"
    environment:
      SERVER1REVERSE_PROXY_LOCATION1: /
      SERVER1REVERSE_PROXY_PASS1: http://web:8000

  web:
    image: friendsofhoneybee/nginx:1.11
    ports:
      - "8000:8000"
    links:
      - couchdb:couchdb
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    volumes:
      - ../../:/var/www
      - ../logs:/var/log/supervisor
      - ../logs:/var/log/php
      - ../environment:/usr/local/env
      - ./nginx:/etc/nginx/conf.d
      - ./php/fpm:/etc/php5/fpm/conf.d/custom.d
    environment:
      LOCAL_CONFIG_DIR: /usr/local/env
      PHP_INI_SCAN_DIR: :/etc/php5/fpm/conf.d/custom.d
      APP_ENV: dev

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    volumes:
      - ../../data/couchdb:/usr/local/var/lib/couchdb

  elasticsearch:
    image: friendsofhoneybee/elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: friendsofhoneybee/rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: honeylex
      RABBITMQ_DEFAULT_PASS: honeylex