version: '3'
services:
  proxy:
    image: blacklabelops/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_REDIRECT_PORT80: "true"

      SERVER1SERVER_NAME: ${SERVER_HOST}
      SERVER1HTTP_ENABLED: "false"
      SERVER1HTTPS_ENABLED: "true"
      SERVER1CERTIFICATE_DNAME: /CN=Honeylex/OU=Honeylex/O=${SERVER_HOST}/L=Berlin/C=DE
      SERVER1REVERSE_PROXY_LOCATION1: /
      SERVER1REVERSE_PROXY_PASS1: http://nginx:8000

  nginx:
    image: nginx:stable
    command: ["nginx", "-c", "/var/www/var/docker/nginx/conf/nginx.conf", "-g", "daemon off;"]
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - php_fpm:php_fpm
    volumes:
      - ../../:/var/www
      - ../logs:/var/log/nginx

  php_cli:
    image: friendsofhoneybee/php:5.6-cli
    working_dir: /var/www
    links:
      - couchdb:couchdb
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    volumes:
      - ../../:/var/www
      - ../logs:/var/log
    environment:
      SERVER_HOST: ${SERVER_HOST}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      LOCAL_CONFIG_DIR: ${LOCAL_CONFIG_DIR}
      PHP_INI_SCAN_DIR: ./var/docker/php/cli/conf/conf.d

  php_fpm:
    image: friendsofhoneybee/php:5.6-fpm
    command: ["php-fpm", "--allow-to-run-as-root", "-y", "/var/www/var/docker/php/fpm/conf/php-fpm.d/www.conf"]
    working_dir: /var/www
    ports:
      - "9000:9000"
    links:
      - couchdb:couchdb
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
    volumes:
      - ../../:/var/www
      - ../logs:/var/log
    environment:
      SERVER_HOST: ${SERVER_HOST}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      LOCAL_CONFIG_DIR: ${LOCAL_CONFIG_DIR}
      PHP_INI_SCAN_DIR: ./var/docker/php/fpm/conf/conf.d

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    volumes:
      - ../../data/couchdb:/usr/local/var/lib/couchdb

  elasticsearch:
    image: friendsofhoneybee/elasticsearch:2.4
    command: ["elasticsearch", "--path.conf=/usr/local/env/conf"]
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch:/usr/local/env

  rabbitmq:
    image: friendsofhoneybee/rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}