version: "3.2"
volumes:
  couchdb:
  elasticsearch:
services:
  proxy:
    environment:
      SERVER1CERTIFICATE_DNAME: /CN=Honeylex/OU=Honeylex/O=${HOST_NAME}/L=Berlin/C=DE
      SERVER2CERTIFICATE_DNAME: /CN=Honeylex/OU=Honeylex/O=api.${HOST_NAME}/L=Berlin/C=DE
      SERVER1REVERSE_PROXY_DIRECTIVE1FIELD1: proxy_read_timeout 3000
      SERVER2REVERSE_PROXY_DIRECTIVE1FIELD1: proxy_read_timeout 3000

  nginx:
    volumes:
      - ../../:/var/www

  php:
    volumes:
      - ../../:/var/www

  couchdb:
    volumes:
      - couchdb:/usr/local/var/lib/couchdb

  elasticsearch:
    volumes:
      - ./elasticsearch/conf:/usr/share/elasticsearch/config:ro
      - elasticsearch:/usr/share/elasticsearch/data

  elasticsearch-head:
    image: mobz/elasticsearch-head:2
    ports:
      - "9100:9100"